### ISSUE TITLE
Newest Version of fastavro cannot read test avro files.

### ISSUE THREAD

**Issue by JGSweets** [capitalone/DataProfiler#219]
**General Information:**
 - OS: MacOS
 - Python version: 3.8.7
 - Library version: 0.4.5

`fastavro==1.4.1`

**Describe the bug:**
Tests failing when reading avro test files.

**To Reproduce:**
```python
import dataprofiler as dp


input_file_path = 'dataprofiler/tests/data/avro/users.avro'
data = dp.Data(input_file_path)
len(data)
```

```python
import fastavro


input_file_path = 'dataprofiler/tests/data/avro/users.avro'
with open(input_file_path, "rb") as input_file:
    fastavro.reader(input_file)
```

error:
```
Traceback (most recent call last):
  File "....", line 2, in <module>
    fastavro.reader(input_file)
  File "fastavro/_read.pyx", line 1134, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 1106, in fastavro._read.file_reader.__init__
  File "fastavro/_schema.pyx", line 78, in fastavro._schema.parse_schema
KeyError: '__named_schemas'
```

**Comment by JGSweets** [comment]
`deflate_compressed_intentionally_mislabeled_file.csv` and `snappy_compressed_intentionally_mislabeled_file.csv` also fail.

It might fail specifically on files with a compression.

**Comment by JGSweets** [comment]
It is not bc of compression as it seems it has to do with files which were re-saved via fastavro on an older version.

The older version does not contain the dict key `__named_schemas` in the format which likely causes the problem.
