### ISSUE TITLE
diff_report = profile1.diff(profile2) -> Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by lettergram** [capitalone/DataProfiler#442]
**General Information:**
 - OS: OSX
 - Python version: python 3.8
 - Library version: current

**Describe the bug:**

```
Object of type int64 is not JSON serializable
```

Problem:

```
'conservative': {'df': xxxx, 'p-value': 0.0}, 'welch': {'df': xxxx, 'p-value': 0.0}}
```

**To Reproduce:**

```python
diff_report = profile1.diff(profile2)
json.dumps(diff_report)
```

**Expected behavior:**

**Screenshots:**

**Additional context:**

**Comment by lettergram** [comment]
FYI: I ran into the same issue with `sets` in the null types.

Might just want to ensure you can run `json.dumps`

**Comment by micdavis** [comment]
I am working on this issue.

**Comment by lettergram** [comment]
?

**Comment by micdavis** [comment]
This is fixed in this release: https://github.com/capitalone/DataProfiler/releases/tag/0.7.7

**Comment by turtlemonvh** [comment]
I'm hitting something similar on v0.7.10

```
Traceback (most recent call last):
  File "profile_capone.py", line 13, in <module>
    json.dump(readable_report, f, indent=4)
  File "/home/timothy/anaconda3/lib/python3.8/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 376, in _iterencode_dict
    raise TypeError(f'keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not int64
```

**Comment by taylorfturner** [comment]
> I'm hitting something similar on v0.7.10
> 
> 
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "profile_capone.py", line 13, in <module>
> 
>     json.dump(readable_report, f, indent=4)
> 
>   File "/home/timothy/anaconda3/lib/python3.8/json/__init__.py", line 179, in dump
> 
>     for chunk in iterable:
> 
>   File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 431, in _iterencode
> 
>     yield from _iterencode_dict(o, _current_indent_level)
> 
>   File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
> 
>     yield from chunks
> 
>   File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
> 
>     yield from chunks
> 
>   File "/home/timothy/anaconda3/lib/python3.8/json/encoder.py", line 376, in _iterencode_dict
> 
>     raise TypeError(f'keys must be str, int, float, bool or None, '
> 
> TypeError: keys must be str, int, float, bool or None, not int64
> 
> ```

Hey Timothy! Can you pop a snippet of exactly what you are running to recreate the issue? Thanks for raising this!

**Comment by turtlemonvh** [comment]
Yep - I can't share the data, but the code is pretty much straight out of your readme.

```
import json
from dataprofiler import Data, Profiler
import numpy as np

data = Data("some-data.csv") # Auto-Detect & Load: CSV, AVRO, Parquet, JSON, Text, URL

print(data.data.head(5)) # Access data directly via a compatible Pandas DataFrame

profile = Profiler(data) # Calculate Statistics, Entity Recognition, etc

# https://capitalone.github.io/DataProfiler/docs/0.7.10/html/profiler.html
for foption in ["pretty", "compact", "serializable", "flat"]:
    try:
        print(f"Trying option: {foption}")
        readable_report = profile.report(report_options={"output_format": foption})

        with open("capone_profile.json", "w+") as f:
            json.dump(readable_report, f, indent=4)
    except TypeError as e:
        print(e)
        pass
```

I'll take a look at the structure of the `Profiler` object now to see if anything pops out.

**Comment by turtlemonvh** [comment]
On a quick glance maybe it is `quantiles`? That has int keys. IDK if they are int64 at the time you pass the object to the JSON serializer.

But this works fine, so maybe not.

```
In [25]: json.dumps(profile.report()['data_stats'][1]['statistics']['quantiles'])
```

**Comment by turtlemonvh** [comment]
Ah nevermind, I think its this one.

```
In [32]: json.dumps(profile.report()['global_stats']['profile_schema'])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-32-a20969264527> in <module>
----> 1 json.dumps(profile.report()['global_stats']['profile_schema'])

~/anaconda3/lib/python3.8/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    229         cls is None and indent is None and separators is None and
    230         default is None and not sort_keys and not kw):
--> 231         return _default_encoder.encode(obj)
    232     if cls is None:
    233         cls = JSONEncoder

~/anaconda3/lib/python3.8/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

~/anaconda3/lib/python3.8/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be str, int, float, bool or None, not numpy.int64
```

**Comment by turtlemonvh** [comment]
Yeah that worked.

```python
readable_report = profile.report(report_options={"output_format": "serializable"})

# Error
json.dumps(readable_report)

# OK
del readable_report['global_stats']['profile_schema']
json.dumps(readable_report)
```

**Comment by taylorfturner** [comment]
Oh okay.  So this error is not on `diff()` its on `json.dumps(report)`.

**Comment by turtlemonvh** [comment]
Ah yes, sorry - I didn't read this ticket closely enough. 😅

**Comment by taylorfturner** [comment]
No worries at all

I am testing the following but unable to re-create the issue
```
import json
import dataprofiler as dp
import numpy as np

data = dp.Data('dataprofiler/tests/data/csv/guns.csv')
profile = dp.Profiler(data)
readable_report = profile.report(report_options={"output_format": "serializable"})
json.dumps(readable_report)
```

**Comment by JGSweets** [comment]
@taylorfturner this might be dataset dependent, e.g. if the dataset itself has columns.

**Comment by taylorfturner** [comment]
Yeah, that's what I'm thinking too @JGSweets and @turtlemonvh based on the testing I just did

**Comment by taylorfturner** [comment]
@turtlemonvh will close this, but if you have an issue with some example test data please feel free open another issue. Cheers!

**Comment by turtlemonvh** [comment]
Maybe this will help?

```
In [31]: profile.report()['global_stats']['profile_schema']
Out[31]: defaultdict(list, {0: [0], 1: [1], 2: [2], 3: [3], 4: [4], 5: [5], 6: [6]})
```

**Comment by JGSweets** [comment]
@turtlemonvh which version of python?

**Comment by JGSweets** [comment]
Yup, got the bug.

```python
import json

import dataprofiler as dp


data = dp.Data("./dataprofiler/tests/data/csv/iris_no_header.csv")
profiler = dp.Profiler(data)
readable_report = profiler.report(report_options={"output_format": "serializable"})
json.dumps(readable_report)
```

**Comment by taylorfturner** [comment]
yep got it too!

**Comment by JGSweets** [comment]
@turtlemonvh till fix, a work around would be to set the column headers or if profile_schema contains lists(np.int64) to convert them to integers

**Comment by JGSweets** [comment]
Fix incoming soon: @turtlemonvh, ty for identifying the issue!

**Comment by turtlemonvh** [comment]
Excellent - thanks, both!

**Comment by taylorfturner** [comment]
Thank you!

**Comment by JGSweets** [comment]
@turtlemonvh
The fix only alters the profile if serializable is requested such that the profile_schema still matches the original dataframe which was input.
Hence, either `serializable` or `pretty` must be set as the option.

LMK if you think that it should be otherwise.

**Comment by turtlemonvh** [comment]
I ran into this issue using the example in your README (https://github.com/capitalone/DataProfiler/blob/main/README.md), which uses

```python
readable_report = profile.report(report_options={"output_format": "compact"})
print(json.dumps(readable_report, indent=4))
```

So I think it would make sense to either

* Make it so `compact` doesn't hit this serialization error
* Change your example to use `serializable` so people know to use that when dumping to JSON

**Comment by JGSweets** [comment]
#613 should address this for now.
