### ISSUE TITLE
Azure Synapse table with uniqueidentifier columns fails to profiler 

### ISSUE THREAD

**Issue by dilkushpatel** [capitalone/DataProfiler#674]
I have lots of tables with multiple columns of type uniqueidentifier
when I run them through data profiler i get below error

Errored for schema name : P360    table name : Staging_InsertQ4Alignmnets
An error occurred while calling o1225.getResult.
: org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:429)
	at org.apache.spark.security.SocketAuthServer.getResult(SocketAuthServer.scala:107)
	at org.apache.spark.security.SocketAuthServer.getResult(SocketAuthServer.scala:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.databricks.spark.sqldw.SqlDWSideException: Azure Synapse Analytics failed to execute the JDBC query produced by the connector.
Underlying SQLException(s):
  - com.microsoft.sqlserver.jdbc.SQLServerException: Columns with UniqueIdentifier types are not supported in external tables. [ErrorCode = 102050] [SQLState = S0001]
         
	at com.databricks.spark.sqldw.Utils$.wrapExceptions(Utils.scala:723)
	at com.databricks.spark.sqldw.SqlDWRelation.buildScan(SqlDWRelation.scala:116)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$apply$3(DataSourceStrategy.scala:455)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$pruneFilterProject$1(DataSourceStrategy.scala:490)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:570)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:489)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:455)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:69)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:69)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:100)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$4(QueryPlanner.scala:85)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:82)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:100)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:78)
	at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:625)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:215)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:151)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:265)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:973)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:265)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:215)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:208)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:227)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:973)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:227)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:222)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:298)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:365)
	at org.apache.spark.sql.execution.QueryExecution.explainStringLocal(QueryExecution.scala:329)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:203)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:388)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:187)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:973)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:338)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4044)
	at org.apache.spark.sql.Dataset.$anonfun$collectAsArrowToPython$2(Dataset.scala:3950)
	at org.apache.spark.sql.Dataset.$anonfun$collectAsArrowToPython$2$adapted(Dataset.scala:3949)
	at org.apache.spark.security.SocketAuthServer$.$anonfun$serveToStream$2(SocketAuthServer.scala:153)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1690)
	at org.apache.spark.security.SocketAuthServer$.$anonfun$serveToStream$1(SocketAuthServer.scala:155)
	at org.apache.spark.security.SocketAuthServer$.$anonfun$serveToStream$1$adapted(SocketAuthServer.scala:150)
	at org.apache.spark.security.SocketFuncServer.handleConnection(SocketAuthServer.scala:124)
	at org.apache.spark.security.SocketFuncServer.handleConnection(SocketAuthServer.scala:117)
	at org.apache.spark.security.SocketAuthServer$$anon$1.$anonfun$run$4(SocketAuthServer.scala:70)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.security.SocketAuthServer$$anon$1.run(SocketAuthServer.scala:70)
Caused by: java.sql.SQLException: Exception thrown in awaitResult: 
	at com.databricks.spark.sqldw.JDBCWrapper.executeInterruptibly(SqlDWJDBCWrapper.scala:137)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$1(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$1$adapted(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.withPreparedStatement(SqlDWJDBCWrapper.scala:362)
	at com.databricks.spark.sqldw.JDBCWrapper.executeInterruptibly(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.createExternalTable(SqlDWJDBCWrapper.scala:536)
	at com.databricks.spark.sqldw.JDBCWrapper.withExternalTable(SqlDWJDBCWrapper.scala:548)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$5(SqlDWRelation.scala:241)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.sqldw.JDBCWrapper.withTempFileFormat(SqlDWJDBCWrapper.scala:523)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$4(SqlDWRelation.scala:241)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.sqldw.JDBCWrapper.withDataSource(SqlDWJDBCWrapper.scala:489)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$3(SqlDWRelation.scala:240)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$3$adapted(SqlDWRelation.scala:237)
	at com.databricks.spark.sqldw.JDBCWrapper.withAzureStorageCredential(SqlDWJDBCWrapper.scala:445)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$2(SqlDWRelation.scala:237)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$2$adapted(SqlDWRelation.scala:235)
	at com.databricks.spark.sqldw.JDBCWrapper.withConnection(SqlDWJDBCWrapper.scala:340)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$1(SqlDWRelation.scala:235)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.ProgressReporter$.withStatusCode(ProgressReporter.scala:364)
	at com.databricks.spark.util.SparkDatabricksProgressReporter$.withStatusCode(ProgressReporter.scala:34)
	at com.databricks.spark.sqldw.SqlDWRelation.getRDDFromBlobStore(SqlDWRelation.scala:235)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$buildScan$1(SqlDWRelation.scala:149)
	at com.databricks.spark.sqldw.Utils$.wrapExceptions(Utils.scala:692)
	... 63 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Columns with UniqueIdentifier types are not supported in external tables.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqls

*** WARNING: max output size exceeded, skipping output. ***

cala:298)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:365)
	at org.apache.spark.sql.execution.QueryExecution.explainStringLocal(QueryExecution.scala:329)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:203)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:388)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:187)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:973)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:338)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4044)
	at org.apache.spark.sql.Dataset.$anonfun$collectAsArrowToPython$2(Dataset.scala:3950)
	at org.apache.spark.sql.Dataset.$anonfun$collectAsArrowToPython$2$adapted(Dataset.scala:3949)
	at org.apache.spark.security.SocketAuthServer$.$anonfun$serveToStream$2(SocketAuthServer.scala:153)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1690)
	at org.apache.spark.security.SocketAuthServer$.$anonfun$serveToStream$1(SocketAuthServer.scala:155)
	at org.apache.spark.security.SocketAuthServer$.$anonfun$serveToStream$1$adapted(SocketAuthServer.scala:150)
	at org.apache.spark.security.SocketFuncServer.handleConnection(SocketAuthServer.scala:124)
	at org.apache.spark.security.SocketFuncServer.handleConnection(SocketAuthServer.scala:117)
	at org.apache.spark.security.SocketAuthServer$$anon$1.$anonfun$run$4(SocketAuthServer.scala:70)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.security.SocketAuthServer$$anon$1.run(SocketAuthServer.scala:70)
Caused by: java.sql.SQLException: Exception thrown in awaitResult: 
	at com.databricks.spark.sqldw.JDBCWrapper.executeInterruptibly(SqlDWJDBCWrapper.scala:137)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$1(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$1$adapted(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.withPreparedStatement(SqlDWJDBCWrapper.scala:362)
	at com.databricks.spark.sqldw.JDBCWrapper.executeInterruptibly(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.createExternalTable(SqlDWJDBCWrapper.scala:536)
	at com.databricks.spark.sqldw.JDBCWrapper.withExternalTable(SqlDWJDBCWrapper.scala:548)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$5(SqlDWRelation.scala:241)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.sqldw.JDBCWrapper.withTempFileFormat(SqlDWJDBCWrapper.scala:523)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$4(SqlDWRelation.scala:241)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.sqldw.JDBCWrapper.withDataSource(SqlDWJDBCWrapper.scala:489)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$3(SqlDWRelation.scala:240)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$3$adapted(SqlDWRelation.scala:237)
	at com.databricks.spark.sqldw.JDBCWrapper.withAzureStorageCredential(SqlDWJDBCWrapper.scala:445)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$2(SqlDWRelation.scala:237)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$2$adapted(SqlDWRelation.scala:235)
	at com.databricks.spark.sqldw.JDBCWrapper.withConnection(SqlDWJDBCWrapper.scala:340)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$getRDDFromBlobStore$1(SqlDWRelation.scala:235)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.ProgressReporter$.withStatusCode(ProgressReporter.scala:364)
	at com.databricks.spark.util.SparkDatabricksProgressReporter$.withStatusCode(ProgressReporter.scala:34)
	at com.databricks.spark.sqldw.SqlDWRelation.getRDDFromBlobStore(SqlDWRelation.scala:235)
	at com.databricks.spark.sqldw.SqlDWRelation.$anonfun$buildScan$1(SqlDWRelation.scala:149)
	at com.databricks.spark.sqldw.Utils$.wrapExceptions(Utils.scala:692)
	... 63 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Columns with UniqueIdentifier types are not supported in external tables.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$2(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$2$adapted(SqlDWJDBCWrapper.scala:115)
	at com.databricks.spark.sqldw.JDBCWrapper.$anonfun$executeInterruptibly$3(SqlDWJDBCWrapper.scala:129)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Any thought around what would this fail?

**Comment by taylorfturner** [comment]
Hey, @dilkushpatel! Thanks for testing out the dataprofiler and raising this issue. 

Not exactly sure your setup or the code you are running; however, I'd point you to this documentation for the dataprofiler for the `DataReader`. Data Profiler supports reading in data with the `dp.Data` class for the data types listed in the documentation [here](https://capitalone.github.io/DataProfiler/docs/0.8.0/html/data_readers.html#data-readers). 

Let me know if you have any more questions. Thx!

**Comment by dilkushpatel** [comment]
So I'm using Pandas dataframe as source

Snippet of code:
        pandasDF = df.toPandas()

        data = Data(data=pandasDF, data_type='csv')

        profile = Profiler(data)

        readable_report = profile.report(report_options={"output_format": "Compact"})
    
        input_tab_df.loc[len(input_tab_df.index)] = [schema_nm,table_nm,readable_report['global_stats']['row_count'],readable_report['global_stats']['row_has_null_ratio'],readable_report['global_stats']['row_is_null_ratio'],readable_report['global_stats']['duplicate_row_count'],readable_report['global_stats']['column_count']]



Its running in databricks and getting data from SQL Azure DW

        df = spark.read \
          .format("com.databricks.spark.sqldw") \
          .option("url", "jdbc:sqlserver://<server name>;database=<DB>;user=<user>@<server>;password=<Password>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.sql.azuresynapse.net;loginTimeout=30;") \
          .option("tempDir", "abfss://<container>@<dfs storage>/logs") \
          .option("forwardSparkAzureStorageCredentials", "true") \
          .option("dbTable", schema_nm+'.'+table_nm) \
          .load()


It fails for all tables which have uniqueidentifier column
also failed on some for weird reason but I'm checking on those.

**Comment by JGSweets** [comment]
@dilkushpatel 
Could it be related to:
https://learn.microsoft.com/en-us/answers/questions/246875/how-to-read-uniqueidentifier-into-spark-notebook-i.html

**Comment by dilkushpatel** [comment]
Interesting
You are correct, uniqueidentifier seems to be an issue
